from pydantic import BaseModel
from typing import List, Optional, Any, Dict

# =========================================================================
# 📥 REQUEST MODELS (What the Frontend UI sends to the Backend)
# =========================================================================

class AIAssistantRequest(BaseModel):
    """
    🔵 NEW: Payload model for the AI Assistant's chat endpoint.
    This model captures the user's new chat message (e.g., 'bags')
    AND their current search state (e.g., 'searching for red nike shoes').
    This context is critical for the AI to decide if the user is refining
    shoes or switching to a totally new product.
    """
    chat_message: str
    current_state: 'SearchRequest' # Captures the whole active SearchRequest payload


class PriceFilter(BaseModel):
    """Defines min/max boundaries for price filtering."""
    min: Optional[float] = None
    max: Optional[float] = None


class Filters(BaseModel):
    """
    Structured object representing the exact state of the UI filters sidebar.
    Values are populated by UI interaction (checkboxes/prices). The AI
    Assistant will now dynamically update these arrays based on semantic intent.
    """
    price: Optional[PriceFilter] = None
    brand: Optional[List[str]] = None
    category: Optional[List[str]] = None
    in_stock: Optional[bool] = None
    
    # 🟢 DYNAMIC FILTERS: Extracted by the AI from semantic chat intent
    color: Optional[List[str]] = None
    # GENDER HAS BEEN REMOVED FROM THIS MODEL AS REQUESTED


class SearchRequest(BaseModel):
    """
    The master payload for the main search API (/search).
    This encapsulates the user's search text, active filters, sorting methods,
    and pagination state (page 1, page 2...) passed to OpenSearch.
    """
    query: str  # The main search input (e.g., 'shoes', 'iphone', 'athera home')
    
    # PAGINATION CONTROLS
    page: int = 1        # The UI changes this to 2, 3, 4... for paging
    page_size: int = 25  # keeps grid nice. AI assistant will overwrite to 10.
    
    filters: Optional[Filters] = None  # The nested filter object (see Filters class above)
    sort: str = "best_matches"        # The sorting method chosen in the UI dropdown


# =========================================================================
# 📤 RESPONSE MODELS (What the Backend sends to the Frontend)
# =========================================================================

class SearchResponse(BaseModel):
    """
    The structured response sent back after a standard search.
    It contains the products, filter data, and pagination math that the
    Javascript uses to dynamically redraw the whole product grid and sidebar.
    """
    # PAGINATION DATA: Used by UI to draw buttons (1, 2, 3...)
    total_results: int
    total_pages: int
    current_page: int
    
    pagination_html: Optional[str] = "" # Pre-rendered Python pagination buttons
    
    # MAIN DATA PACKETS
    # List of product dictionaries with normalized AI best match scores, images, prices...
    results: List[Dict[str, Any]]
    # Dictionary of dynamic facets (Brands, categories) with document counts for the UI sidebar.
    facets: Dict[str, Any]
    
    error: Optional[str] = None # Passes backend errors to the UI gracefully


class AIAssistantResponse(SearchResponse):
    """
    🔴 NEW: Specialized response model for the AI Assistant.
    It inherits everything from SearchResponse but adds two fields so the
    frontend can automatically synchronize the product grid with the AI's decision.
    """
    ai_message: Optional[str] = "" # A friendly, contextual 1-sentence reply generated by the LLM
    updated_query: Optional[str] = None # The AI's decision on the new primary query (e.g., 'bags')
    updated_filters: Optional[Dict[str, Any]] = None # The AI's decision on the new filter arrays