from pydantic import BaseModel
from typing import List, Optional, Any, Dict

# =========================================================================
# 📥 REQUEST MODELS (What the Frontend UI sends to the Backend)
# These models validate the incoming JSON payloads from your Javascript fetch()
# calls to ensure they match the expected data types before processing the query.
# =========================================================================

class AIQuery(BaseModel):
    """
    Payload model specifically for the AI Assistant's chat endpoint.
    Captures the raw user message typed into the AI panel (e.g., 'show me red shoes for women').
    """
    query: str

class PriceFilter(BaseModel):
    """
    Defines the minimum and maximum boundaries for the price range filter.
    Both fields are optional, allowing for 'Under $50' (max only) or 'Over $100' (min only) searches.
    """
    min: Optional[float] = None
    max: Optional[float] = None

class Filters(BaseModel):
    """
    Represents the exact state of the UI sidebar filters.
    When a user checks boxes or enters prices in the UI, those values
    are populated here as lists of strings or boolean values. The AI Assistant
    can also inject values directly into these arrays based on semantic intent.
    """
    price: Optional[PriceFilter] = None
    brand: Optional[List[str]] = None      # e.g., ["Apple", "Samsung"]
    category: Optional[List[str]] = None   # e.g., ["Electronics", "Phones"]
    in_stock: Optional[bool] = None        # True if 'In Stock Only' checkbox is clicked
    
    # 🟢 Dynamic Filters extracted from UI static checkboxes or AI semantic intent
    color: Optional[List[str]] = None      # e.g., ["black", "red"]
class SearchRequest(BaseModel):
    """
    The master payload for the main search API (/search).
    This encapsulates the user's text query, active filters, sorting preference,
    and pagination state into a single object passed to the search_service.
    """
    query: str  # The main search bar input OR the AI's extracted core product query
    
    # 🔥 PAGINATION CONTROLS 🔥
    page: int = 1        # The current page number requested by the UI (default: 1)
    page_size: int = 25  # Number of products to return per page (25 for the main grid, 10 for AI chat)
    
    filters: Optional[Filters] = None  # The nested filter object (see Filters class above)
    sort: str = "relevance"            # Sorting method selected in UI dropdown (e.g., 'price_asc', 'weighted')


# =========================================================================
# 📤 RESPONSE MODELS (What the Backend sends back to the Frontend UI)
# These models dictate exactly how the JSON response is structured so the
# Javascript frontend knows how to parse and dynamically render the grid.
# =========================================================================

class SearchResponse(BaseModel):
    """
    The structured response returned by the search engine after querying AWS OpenSearch.
    Contains the matching products, updated filter counts (facets), and pagination math.
    """
    # 🔥 PAGINATION METADATA 🔥
    total_results: int     # Total number of products matching the query across all pages
    total_pages: int       # Total pages available (calculated as total_results / page_size)
    current_page: int      # The page currently being viewed
    
    # Pre-rendered HTML string containing the pagination buttons (1, 2, 3...) generated by Python
    pagination_html: Optional[str] = ""
    
    # 📦 MAIN DATA 📦
    # List of product dictionaries containing normalized AI scores, images, prices, titles, etc.
    results: List[Dict[str, Any]]
    
    # Dictionary of dynamic facets (Brands, Categories) with their document counts for the UI sidebar
    facets: Dict[str, Any]
    
    # Optional field to pass backend errors (like OpenSearch timeouts) to the frontend gracefully
    error: Optional[str] = None